import type {
  AntiSimplificationReport,
  ClaimGraph,
  CriticCouncilReport,
  DecisionLedger,
  DomainAnalysis,
  EvidenceLedger,
  EvidenceMap,
  ExecutionTaskGraph,
  ProblemResolutionPlan,
  ProductExpansion,
  ProductIntentModel,
  ProductizationForecast,
  ReconstructedIntent,
  ResearchPlan,
  RouteDeepDiveReport,
  SelectedRoute,
  StrategyCandidate,
  StrategyRevisionReport,
  SynthesizedCapability,
  TechnicalRoutePlan,
  TechnicalRouteScorecard,
  TechnicalSolutionCandidates,
  TechnicalSolutionDecisionMatrix,
  TechnicalSolutionIntegrationPlan,
  TechnicalSolutionResearchPlan,
  TechnicalSolutionSearchResults,
} from "../types/artifacts.js";

interface FinalThinkingReportInput {
  domainAnalysis: DomainAnalysis;
  intent: ReconstructedIntent;
  productIntent: ProductIntentModel;
  synthesizedCapabilities: SynthesizedCapability[];
  expansion: ProductExpansion;
  researchPlan: ResearchPlan;
  evidenceMap: EvidenceMap;
  evidenceLedger: EvidenceLedger;
  claimGraph?: ClaimGraph;
  strategies: StrategyCandidate[];
  routeDeepDive?: RouteDeepDiveReport;
  revisionHistory?: StrategyRevisionReport[];
  technicalRoutePlan?: TechnicalRoutePlan;
  productizationForecast?: ProductizationForecast;
  problemResolutionPlan?: ProblemResolutionPlan;
  technicalRouteScorecard?: TechnicalRouteScorecard;
  technicalSolutionResearchPlan?: TechnicalSolutionResearchPlan;
  technicalSolutionSearchResults?: TechnicalSolutionSearchResults;
  technicalSolutionCandidates?: TechnicalSolutionCandidates;
  technicalSolutionDecisionMatrix?: TechnicalSolutionDecisionMatrix;
  technicalSolutionIntegrationPlan?: TechnicalSolutionIntegrationPlan;
  antiSimplificationReport: AntiSimplificationReport;
  councilReport: CriticCouncilReport;
  selectedRoute: SelectedRoute;
  taskGraph: ExecutionTaskGraph;
  decisionLedger: DecisionLedger;
  partialAgentRun?: boolean;
  enabledAgents?: string[];
}

export function buildFinalThinkingReport(input: FinalThinkingReportInput): string {
  const selectedAggregate = input.councilReport.aggregate.find(
    (item) => item.strategyId === input.selectedRoute.selectedStrategyId,
  );
  const partialSmokeNotice = input.partialAgentRun
    ? [
        "## Partial Smoke Notice",
        "",
        "This is a partial LLM smoke run; downstream artifacts are not fully regenerated by LLM.",
        `LLM-enabled smoke agents: ${(input.enabledAgents ?? []).join(", ") || "none"}.`,
        "Artifacts after disabled agents may use deterministic rule outputs, so this report must not be read as a complete full-pipeline LLM result.",
        "",
      ].join("\n")
    : "";
  const productIntentSignals = [
    input.productIntent.rawGoal,
    input.productIntent.normalizedGoal,
    input.productIntent.domainId,
    ...input.productIntent.primaryActors,
    ...input.productIntent.secondaryActors,
    ...input.productIntent.coreResources,
    ...input.productIntent.coreWorkflows,
    ...input.productIntent.riskSurfaces,
  ]
    .filter(Boolean)
    .slice(0, 28)
    .join(", ");

  return `# Final Thinking Report

${partialSmokeNotice}
## Goal

${input.intent.rawGoal}

## Reconstructed Intent

- Detected domain: ${input.domainAnalysis.domainId} (${input.domainAnalysis.domainName})
- Domain confidence: ${input.domainAnalysis.confidence}
- Matched signals: ${input.domainAnalysis.matchedSignals.length > 0 ? input.domainAnalysis.matchedSignals.join(", ") : "none"}
- Domain reasoning: ${input.domainAnalysis.reasoningSummary}
- Category: ${input.intent.inferredProductCategory}
- Normalized goal: ${input.intent.normalizedGoal}
- Primary users: ${input.intent.primaryUsers.join(", ")}

## Product Intent Model

- Product intent domain: ${input.productIntent.domainId}
- Product intent raw goal: ${input.productIntent.rawGoal}
- Product intent normalized goal: ${input.productIntent.normalizedGoal}
- Product intent signals: ${productIntentSignals}
- Primary actors: ${input.productIntent.primaryActors.join(", ")}
- Secondary actors: ${input.productIntent.secondaryActors.join(", ")}
- Core resources: ${input.productIntent.coreResources.join(", ")}
- Core workflows: ${input.productIntent.coreWorkflows.join(", ")}
- Data objects: ${input.productIntent.dataObjects.join(", ")}
- Lifecycle stages: ${input.productIntent.lifecycleStages.join(", ")}
- Permission boundaries: ${input.productIntent.permissionBoundaries.join("; ")}
- Risk surfaces: ${input.productIntent.riskSurfaces.join(", ")}
- Operational needs: ${input.productIntent.operationalNeeds.join(", ")}
- Reporting needs: ${input.productIntent.reportingNeeds.join(", ")}
- Integration needs: ${input.productIntent.integrationNeeds.join(", ")}
- Deployment assumptions: ${input.productIntent.deploymentAssumptions.join(", ")}
- Uncertainty notes: ${input.productIntent.uncertaintyNotes.join("; ")}

## Capability Synthesis

Capabilities were synthesized from actors, resources, workflows, risks, operations, reporting, and deployment assumptions before domain-specific enhancement.

${input.synthesizedCapabilities.map((capability) => `- **${capability.name}** (${capability.id}, ${capability.priority}): triggered by ${capability.triggeredBy.slice(0, 4).join(", ")}. Risk if missing: ${capability.riskIfMissing}`).join("\n")}

## Product-Grade Expansion

The goal was expanded into ${input.expansion.coreCapabilities.length} core capabilities, ${input.expansion.operationalCapabilities.length} operational capabilities, and ${input.expansion.nonFunctionalRequirements.length} non-functional requirements.

Key capabilities:

${input.expansion.coreCapabilities.map((capability) => `- ${capability.name}: ${capability.acceptanceSignal}`).join("\n")}

## Research And Evidence Status

This run does not claim completed external research unless accepted sources are present. It creates an Evidence Ledger, Claim Graph, and Decision Ledger while preserving missing-evidence status.

Research questions:

${input.researchPlan.researchQuestions.map((question) => `- ${question.id}: ${question.question}`).join("\n")}

Evidence posture:

${input.evidenceMap.items.map((item) => `- ${item.id}: ${item.claim} (${item.supportType}, ${item.confidence})`).join("\n")}

## Evidence Provider Summary

${(input.evidenceLedger.providersUsed ?? []).map((provider) => `- **${provider.providerId}** (${provider.providerType}): ${provider.evidenceCount} evidence item(s).`).join("\n")}

## Source Quality Summary

- Source quality: ${JSON.stringify(input.evidenceLedger.sourceQualitySummary?.bySourceQuality ?? {})}
- Verification status: ${JSON.stringify(input.evidenceLedger.sourceQualitySummary?.byVerificationStatus ?? {})}
- Evidence strength: ${JSON.stringify(input.evidenceLedger.sourceQualitySummary?.byEvidenceStrength ?? {})}

Observed evidence:

${input.evidenceLedger.evidenceItems.filter((item) => item.verificationStatus === "observed").map((item) => `- ${item.id}: ${item.claim}`).join("\n") || "- none"}

Inferred evidence:

${input.evidenceLedger.evidenceItems.filter((item) => item.verificationStatus === "inferred").slice(0, 8).map((item) => `- ${item.id}: ${item.claim}`).join("\n") || "- none"}

Assumptions and principle-based evidence:

${input.evidenceLedger.evidenceItems.filter((item) => item.verificationStatus === "assumed").slice(0, 8).map((item) => `- ${item.id}: ${item.claim}`).join("\n") || "- none"}

Missing or unverified evidence:

${input.evidenceLedger.evidenceItems.filter((item) => item.verificationStatus === "missing" || item.verificationStatus === "unverified").map((item) => `- ${item.id}: ${item.claim}`).join("\n") || "- none"}

## Evidence Ledger Summary

- Evidence items: ${input.evidenceLedger.evidenceItems.length}
- Assumptions: ${input.evidenceLedger.assumptions.length}
- Missing evidence: ${input.evidenceLedger.missingEvidence.length}
- Inferred claims: ${input.evidenceLedger.inferredClaims.length}
- Weak evidence warnings: ${(input.evidenceLedger.weakEvidenceWarnings ?? []).length}

Key evidence:

${input.evidenceLedger.evidenceItems.slice(0, 8).map((item) => `- **${item.id}** (${item.type}, ${item.sourceType}, ${item.sourceQuality}/${item.evidenceStrength}, ${item.verificationStatus}): ${item.claim}`).join("\n")}

## Claim Graph Summary

- Claims: ${input.claimGraph?.claims.length ?? 0}
- Links: ${input.claimGraph?.links.length ?? 0}
- Unsupported claims: ${input.claimGraph?.unsupportedClaims.length ?? 0}
- Contested claims: ${input.claimGraph?.contestedClaims.length ?? 0}
- Decision-critical claims: ${input.claimGraph?.decisionCriticalClaims.length ?? 0}

Decision-critical claims:

${(input.claimGraph?.decisionCriticalClaims ?? []).map((claim) => `- ${claim}`).join("\n")}

## Unsupported Claims

${(input.claimGraph?.unsupportedClaims ?? []).map((claim) => `- ${claim}`).join("\n") || "- none"}

## Contested Claims

${(input.claimGraph?.contestedClaims ?? []).map((claim) => `- ${claim}`).join("\n") || "- none"}

## Assumption Register

${input.evidenceLedger.assumptions.map((assumption) => `- **${assumption.id}** (${assumption.confidence}): ${assumption.claim}; risk if wrong: ${assumption.riskIfWrong}`).join("\n")}

## Missing Evidence

${input.evidenceLedger.missingEvidence.map((missing) => `- **${missing.id}**: ${missing.question}; impact: ${missing.impact}`).join("\n")}

## Evidence Gaps Accepted

${(input.selectedRoute.evidenceGapsAccepted ?? []).map((gap) => `- ${gap}`).join("\n") || "- none"}

Accepted despite gaps:

${(input.selectedRoute.whyAcceptedDespiteGaps ?? []).map((reason) => `- ${reason}`).join("\n") || "- none"}

## Strategy Candidates

${input.strategies.map((strategy) => `- **${strategy.id} ${strategy.title}**: ${strategy.thesis}`).join("\n")}

## Route Synthesis Rationale

${input.strategies.map((strategy) => `- **${strategy.id} ${strategy.routeArchetype ?? "unspecified"}**: triggered by ${(strategy.triggeredBy ?? []).slice(0, 6).join(", ")}; modules: ${(strategy.modules ?? []).slice(0, 6).join(", ")}; completeness: ${strategy.productCompletenessScore ?? strategy.demoTrapResistanceScore}/10.`).join("\n")}

## Route Deep Dive

${input.routeDeepDive
  ? [
      `Online research: ${input.routeDeepDive.onlineResearchEnabled ? "enabled" : "disabled"}`,
      input.routeDeepDive.routeAnalyses.map((analysis) => [
        `- **${analysis.strategyId} ${analysis.title}**: maturity ${analysis.maturityScore}/10; online sources ${analysis.onlineResearch.sourceCount}.`,
        `  - Online evidence: ${analysis.onlineResearch.sourceCount > 0 && !analysis.onlineResearch.shouldNotUseAsEvidence ? `usable clues (${analysis.onlineResearch.relevance ?? "partial"})` : `外部证据不足 (${analysis.onlineResearch.reason ?? "No high-relevance sources found"})`}`,
        `  - Implementation axes: ${analysis.technicalImplementationAxes.map((axis) => axis.area).join(", ")}`,
        `  - Highest risks: ${analysis.riskRegister.slice(0, 3).map((risk) => `${risk.id}:${risk.severity}:${risk.risk}`).join(" | ")}`,
        `  - Hidden complexities: ${(analysis.hiddenComplexities ?? analysis.likelyHiddenComplexities ?? []).slice(0, 3).join(" | ")}`,
        `  - Operational failure modes: ${(analysis.operationalFailureModes ?? []).slice(0, 2).join(" | ") || "not listed"}`,
        `  - Productization bars: ${analysis.productizationBar.map((bar) => bar.dimension).join(", ")}`,
        `  - Coding blockers to clarify: ${(analysis.validationBeforeCoding ?? analysis.recommendedValidationBeforeCoding).slice(0, 3).join(" | ")}`,
        `  - Test strategy implications: ${(analysis.testStrategyImplications ?? []).slice(0, 2).join(" | ") || "not listed"}`,
      ].join("\n")).join("\n"),
    ].join("\n")
  : "- Route deep dive was not generated."}

## Revision Loop

Triggered: ${(input.revisionHistory ?? []).length > 0 ? "yes" : "no"}

${(input.revisionHistory ?? []).length > 0
  ? (input.revisionHistory ?? []).map((revision) => [
      `- Round ${revision.revisionRound}: ${revision.reasonForRevision}`,
      `  - Blocking issues addressed: ${revision.blockingIssuesAddressed.slice(0, 6).join(" | ") || "none"}`,
      `  - Unresolved blocking issues: ${revision.unresolvedBlockingIssues.slice(0, 6).join(" | ") || "none"}`,
      `  - Changed strategies: ${revision.strategyChangeLog.map((item) => `${item.strategyId}:${item.changedFields.join(",")}`).join(" | ")}`,
      `  - Can re-run selection: ${revision.canReRunSelection ? "yes" : "no"}`,
      `  - Stop reason: ${revision.stopReason}`,
    ].join("\n")).join("\n")
  : "- No revision loop was triggered."}

Revision final coding handoff: ${input.selectedRoute.canProceedToCoding === false ? "blocked" : "allowed after readiness checks"}

${input.selectedRoute.canProceedToCoding === false ? "Do not hand off to Coding Agent yet." : "Revision loop did not leave route in blocked state."}

## Technical Productization Plan

Recommended technical route: ${input.selectedRoute.selectedStrategyId}: ${input.selectedRoute.selectedTitle}

Coding readiness inherited by technical scorecard: ${input.technicalRouteScorecard?.canProceedToCoding === false ? "blocked" : "not blocked by scorecard"}

${input.technicalRouteScorecard?.canProceedToCoding === false ? "Do not hand off to Coding Agent yet." : "Technical scorecard does not add a coding block beyond normal readiness review."}

Why not microservices-first:

- The current artifact is still a pre-coding productization plan; domain model, workflow state, approval policy, audit policy, and integration contracts must stabilize before service decomposition.
- A modular monolith with adapter boundaries keeps the hospital rotation domain coherent while preserving later extraction options.

Why not a single-page demo:

- The route requires rotation lifecycle state, capacity conflict detection, approval workflow, audit trail, import/export, backup, and integration boundaries.
- A page-only demo would hide capacity changes, make-up rotation rules, mentor responsibility history, manual attendance override risk, and archived accountability.

Core data models:

${(input.technicalRoutePlan?.routes ?? []).slice(0, 3).map((route) => `- **${route.strategyId} ${route.routeTitle}**: ${(route.databaseModel?.entities ?? []).slice(0, 8).map((entity) => entity.name).join(", ")}`).join("\n") || "- Technical route plan was not generated."}

Core state machines:

${(input.technicalRoutePlan?.routes ?? []).slice(0, 3).map((route) => `- **${route.strategyId}**: ${(route.stateMachines ?? []).map((machine) => `${machine.name} (${(machine.states ?? []).slice(0, 5).join(" -> ")})`).join(" | ")}`).join("\n") || "- none"}

Conflict detection strategy:

${(input.technicalRoutePlan?.routes ?? []).slice(0, 3).map((route) => `- **${route.strategyId}**: ${(route.conflictDetectionModel?.rules ?? []).slice(0, 5).join(" | ")}`).join("\n") || "- none"}

Permission and audit strategy:

${(input.technicalRoutePlan?.routes ?? []).slice(0, 3).map((route) => `- **${route.strategyId}** permissions: ${(route.permissionModel?.boundaries ?? []).slice(0, 4).join(" | ")}; audit: ${(route.auditLogModel?.events ?? []).slice(0, 5).join(" | ")}`).join("\n") || "- none"}

Deployment and operations strategy:

${(input.technicalRoutePlan?.routes ?? []).slice(0, 3).map((route) => `- **${route.strategyId}** deployment: ${(route.deploymentTopology ?? []).join(" | ")}; observability: ${(route.observabilityPlan ?? []).slice(0, 5).join(" | ")}`).join("\n") || "- none"}

## Productization Forecast

Most likely productization problems:

${(input.productizationForecast?.items ?? []).slice(0, 10).map((item) => `- **${item.id}** ${item.scenario} Countermeasure: ${item.designCountermeasure}`).join("\n") || "- Productization forecast was not generated."}

## Problem Resolution Plan

Engineering resolution plan:

${(input.problemResolutionPlan?.problems ?? []).slice(0, 10).map((item) => [
  `- **${item.problem}**`,
  `  - Solution: ${item.recommendedSolution}`,
  `  - Data: ${item.dataModelChange.slice(0, 3).join(" | ")}`,
  `  - Workflow: ${item.workflowChange.slice(0, 3).join(" | ")}`,
  `  - Validation: ${item.validationRule.slice(0, 3).join(" | ")}`,
  `  - Tests: ${item.testCases.slice(0, 3).join(" | ")}`,
  `  - Blocks coding: ${item.blocksCodingUntilResolved ? "yes" : "no"}`,
].join("\n")).join("\n") || "- Problem resolution plan was not generated."}

${input.selectedRoute.canProceedToCoding === false ? "Do not hand off to Coding Agent yet." : ""}

## Problem-Solution Technical Research

Search status: ${input.technicalSolutionSearchResults?.status ?? "not generated"}

${input.technicalSolutionSearchResults?.status === "not_configured" ? "Technical solution search was requested but no live search provider was configured." : ""}

${input.technicalSolutionSearchResults?.status === "disabled" ? "Technical solution search was disabled for this run." : ""}

Research queries by problem:

${(input.technicalSolutionResearchPlan?.problems ?? []).slice(0, 10).map((problem) => `- **${problem.problemId}** ${problem.problemStatement}: ${problem.searchQueries.join(" | ")}`).join("\n") || "- Technical solution research plan was not generated."}

Recommended solution candidates:

${(input.technicalSolutionCandidates?.problems ?? []).slice(0, 10).map((problem) => [
  `- **${problem.problemId}** ${problem.problemStatement}`,
  `  - Recommended: ${problem.recommendedSolution?.name ?? "none"}`,
  `  - Candidate solutions: ${(problem.candidateSolutions ?? []).map((candidate) => candidate.name).join(" | ")}`,
  `  - Rejected: ${(problem.rejectedSolutions ?? []).map((item) => `${item.name}: ${item.reason}`).join(" | ") || "none"}`,
  `  - Source refs: ${(problem.sourceRefs ?? []).join(", ") || (problem.recommendedSolution?.sourceEvidenceStatus === "ruleFallback" ? "ruleFallback, no accepted live source refs" : "none")}`,
  `  - Impact: ${(problem.implementationImpact ?? []).slice(0, 3).join(" | ")}`,
  (problem.sourceRefs ?? []).length === 0 && input.technicalSolutionSearchResults?.status === "completed" ? "  - No high-quality technical solution sources were accepted for this problem." : "",
].filter(Boolean).join("\n")).join("\n") || "- Technical solution candidates were not generated."}

Decision matrix summary:

${(input.technicalSolutionDecisionMatrix?.decisions ?? []).slice(0, 10).map((decision) => `- **${decision.problemId}** selected ${decision.selectedCandidate}; fallback ${decision.fallbackCandidate}; reason: ${decision.selectionReason}`).join("\n") || "- Technical solution decision matrix was not generated."}

Integration impacts:

${(input.technicalSolutionIntegrationPlan?.items ?? []).slice(0, 10).map((item) => [
  `- **${item.problemId}** ${item.selectedSolution}`,
  `  - Data model: ${(item.dataModelChanges ?? []).slice(0, 3).join(" | ")}`,
  `  - Service/API: ${(item.serviceLayerChanges ?? []).slice(0, 2).join(" | ")} / ${(item.apiContractChanges ?? []).slice(0, 2).join(" | ")}`,
  `  - Workflow/permission/audit: ${(item.workflowChanges ?? []).slice(0, 2).join(" | ")} / ${(item.permissionChanges ?? []).slice(0, 2).join(" | ")} / ${(item.auditChanges ?? []).slice(0, 2).join(" | ")}`,
  `  - Tests: ${(item.testingChanges ?? []).slice(0, 3).join(" | ")}`,
  `  - Coding readiness: ${item.impactsCodingReadiness}; still blocks coding: ${item.stillBlocksCoding ? "yes" : "no"}`,
].join("\n")).join("\n") || "- Technical solution integration plan was not generated."}

${input.selectedRoute.canProceedToCoding === false ? "Do not hand off to Coding Agent yet." : ""}

## Anti-Simplification Review

${input.antiSimplificationReport.stance}

Banned shortcuts:

${input.antiSimplificationReport.bannedShortcutSolutions.map((shortcut) => `- ${shortcut}`).join("\n")}

Compositional rule results:

${(input.antiSimplificationReport.compositionalRuleResults ?? []).map((rule) => `- ${rule.ruleId}: ${rule.triggered ? "triggered" : "not triggered"}; requires ${rule.requiredCapability}; ${rule.reason}`).join("\n")}

## Critic Council Summary

Critics: ${input.councilReport.critics.join(", ")}

Aggregate scores:

${input.councilReport.aggregate.map((item) => `- ${item.strategyId}: ${item.averageScore}/10, blocking issues: ${item.blockingIssueCount}`).join("\n")}

## Dissent and Tradeoffs

${input.councilReport.reviews.filter((review) => review.disagreementLevel !== "low" || (review.nearBlockingConcerns ?? []).length > 0).slice(0, 12).map((review) => `- ${review.critic} on ${review.strategyId}: ${review.disagreementLevel}; evidence ${(review.evidenceRefs ?? []).join(", ")}; concerns ${(review.nearBlockingConcerns ?? review.objections).slice(0, 2).join(" | ")}`).join("\n")}

## Selected Route

**${input.selectedRoute.selectedStrategyId}: ${input.selectedRoute.selectedTitle}**

Coding-approved: ${input.selectedRoute.canProceedToCoding === false ? "no" : "yes"}

${input.selectedRoute.canProceedToCoding === false ? "Do not hand off to Coding Agent yet." : "Route can proceed to coding after normal handoff checks."}

Selection status: ${input.selectedRoute.selectionStatus ?? "selected"}

Route planning hypothesis only: ${input.selectedRoute.routeCanBeUsedOnlyAsPlanningHypothesis ? "yes" : "no"}

Blocking reasons:

${(input.selectedRoute.blockingReasons ?? []).map((reason) => `- ${reason}`).join("\n") || "- none"}

Required clarifications before coding:

${(input.selectedRoute.requiredClarificationsBeforeCoding ?? []).map((item) => `- ${item}`).join("\n") || "- none"}

Selection rationale:

${input.selectedRoute.selectionRationale.map((reason) => `- ${reason}`).join("\n")}

Selected aggregate: ${selectedAggregate?.averageScore ?? "n/a"}/10.

Selected route evidence: ${(input.selectedRoute.evidenceRefs ?? []).join(", ")}

Selected route decisions: ${(input.selectedRoute.decisionRefs ?? []).join(", ")}

Selection confidence: ${input.selectedRoute.confidence ?? "n/a"}

Route evidence coverage: ${JSON.stringify(input.selectedRoute.routeEvidenceCoverage ?? {})}

Decisive claims: ${(input.selectedRoute.decisiveClaims ?? []).join(", ")}

Contested claims accepted: ${(input.selectedRoute.contestedClaims ?? []).join(", ")}

Route switch triggers:

${(input.selectedRoute.routeSwitchTriggers ?? []).map((trigger) => `- ${trigger}`).join("\n") || "- none"}

Rejected routes:

${input.selectedRoute.rejectedRoutes.map((route) => `- ${route.strategyId}: ${route.rejectionReason}`).join("\n")}

## Architecture Handoff

The architecture plan is written to \`architecture-plan.md\`. It is a planning artifact only and deliberately contains no implementation code.

## Execution Task Graph

The handoff DAG contains ${input.taskGraph.tasks.length} tasks:

Coding handoff allowed: ${input.taskGraph.canProceedToCoding === false ? "no" : "yes"}

${input.taskGraph.canProceedToCoding === false ? "Do not hand off to Coding Agent yet." : "Task graph may be used by a Coding Agent after normal readiness review."}

Global blocking reasons:

${(input.taskGraph.globalBlockingReasons ?? []).map((reason) => `- ${reason}`).join("\n") || "- none"}

${input.taskGraph.tasks.map((task) => `- ${task.id}: ${task.title} -> ${task.ownerAgent}`).join("\n")}

## Decision Ledger Summary

${input.decisionLedger.decisions.map((decision) => `- **${decision.id}** (${decision.decisionType}, ${decision.confidence}, coverage ${decision.evidenceCoverageScore ?? "n/a"}): selected ${decision.selectedOption}; evidence ${decision.evidenceRefs.join(", ")}; decisive claims ${(decision.decisiveClaimRefs ?? []).join(", ")}; accepted gaps ${(decision.acceptedEvidenceGaps ?? []).join(", ")}`).join("\n")}

## Conditions to Revisit Decisions

${input.decisionLedger.decisions.flatMap((decision) => decision.conditionsToRevisit.map((condition) => `- ${decision.id}: ${condition}`)).slice(0, 16).join("\n")}

## Decisions That Should Be Revisited Before Coding

${input.decisionLedger.decisions
  .filter((decision) => (decision.acceptedEvidenceGaps ?? []).length > 0 || (decision.contestedClaimRefs ?? []).length > 0 || (decision.evidenceCoverageScore ?? 1) < 0.65)
  .map((decision) => `- **${decision.id}**: gaps ${(decision.acceptedEvidenceGaps ?? []).join(", ")}; contested ${(decision.contestedClaimRefs ?? []).join(", ")}; revisit when ${decision.conditionsToRevisit.slice(0, 2).join(" | ")}`)
  .join("\n") || "- none"}

## Explicit Boundary

This run did not create a webpage, dashboard, React page, login page, repository scan, patch, diff viewer, terminal UI, or business implementation. It only produced structured thinking artifacts for a later software development workflow.`;
}