import { commonBadOutputExamples, commonQualityChecklist, jsonInput, thinkingSystemPrompt } from "./common.js";

export const productIntentPrompt = {
  agentName: "ProductIntentBuilder",
  systemPrompt: [
    thinkingSystemPrompt,
    "Output only JSON. Return exactly one JSON object. No markdown. No explanation. No architecture plan. No final report. No implementation details.",
    "Do not wrap the object inside productIntent, intent, data, result, or output. The root object must directly contain every required field.",
    "Every field must appear, even when an array is empty. Never omit rawGoal, normalizedGoal, or domainId.",
    "Use the schema field names exactly. Do not use shorthand keys such as actors, resources, workflows, risks, or needs.",
    "Each array may contain at most 6 items. Keep items short. Each item should stay within 24 Chinese characters when practical.",
    "Actors, resources, workflows, and risks must stay tightly tied to the goal.",
    [
      "Required root JSON template:",
      "{",
      '  "rawGoal": "...",',
      '  "normalizedGoal": "...",',
      '  "domainId": "...",',
      '  "primaryActors": [],',
      '  "secondaryActors": [],',
      '  "coreResources": [],',
      '  "coreWorkflows": [],',
      '  "dataObjects": [],',
      '  "lifecycleStages": [],',
      '  "permissionBoundaries": [],',
      '  "riskSurfaces": [],',
      '  "operationalNeeds": [],',
      '  "reportingNeeds": [],',
      '  "integrationNeeds": [],',
      '  "deploymentAssumptions": [],',
      '  "uncertaintyNotes": []',
      "}",
    ].join("\n"),
  ].join("\n"),
  buildUserPrompt(input: unknown) {
    return jsonInput({
      task: "Build a concrete Product Intent Model from the goal and domain analysis. Keep output compact and schema-only.",
      input,
    });
  },
  outputSchemaName: "product-intent",
  outputSchemaDescription: "Object with actors, resources, workflows, data objects, lifecycle stages, permission boundaries, risk surfaces, operations, reporting, integrations, deployment assumptions, and uncertainty notes.",
  expectedShape: {
    type: "object" as const,
    required: ["rawGoal", "normalizedGoal", "domainId", "primaryActors", "secondaryActors", "coreResources", "coreWorkflows", "dataObjects", "lifecycleStages", "permissionBoundaries", "riskSurfaces", "operationalNeeds", "reportingNeeds", "integrationNeeds", "deploymentAssumptions", "uncertaintyNotes"],
    arrays: [
      { path: "primaryActors" },
      { path: "secondaryActors" },
      { path: "coreResources" },
      { path: "coreWorkflows" },
      { path: "dataObjects" },
      { path: "lifecycleStages" },
      { path: "permissionBoundaries" },
      { path: "riskSurfaces" },
      { path: "operationalNeeds" },
      { path: "reportingNeeds" },
      { path: "integrationNeeds" },
      { path: "deploymentAssumptions" },
      { path: "uncertaintyNotes" },
    ],
  },
  examples: [],
  badOutputExamples: commonBadOutputExamples,
  qualityChecklist: [
    ...commonQualityChecklist,
    "mustNotContain:architecture plan",
    "mustNotContain:final report",
    "mustNotContain:implementation details",
  ],
  temperature: 0.2,
  maxRetries: 2,
};