import { commonBadOutputExamples, commonQualityChecklist, jsonInput, thinkingSystemPrompt } from "./common.js";

export const strategyGeneratorPrompt = {
  agentName: "StrategyGenerator",
  systemPrompt: [
    thinkingSystemPrompt,
    "Output only schema fields. Do not generate a report.",
    "Return exactly one root JSON array. Do not wrap it inside strategies, routes, data, result, or output.",
    "Every route object must use the exact schema field names. All list-shaped fields must be JSON arrays, never paragraphs or strings.",
    "architectureShape, productCoverage, securityAndAbuseResistance, operationalModel, pros, cons, risks, evidenceRefs, modules, conditionsToPreferThisRoute, and conditionsToRejectThisRoute must be arrays.",
    "estimatedComplexity must be one of low, medium, high, very-high.",
    "demoTrapResistanceScore and productCompletenessScore must be numbers from 0 to 10. confidence must be a number from 0 to 1.",
    "Each route must be compact. Limit reasons, risks, and conditions to the most important items.",
    "Each route may contain at most 5 reasons or bullets per list-shaped field.",
    [
      "Route object template:",
      "{",
      '  "id": "S1",',
      '  "title": "...",',
      '  "thesis": "...",',
      '  "targetFit": "...",',
      '  "architectureShape": [],',
      '  "productCoverage": [],',
      '  "securityAndAbuseResistance": [],',
      '  "operationalModel": [],',
      '  "pros": [],',
      '  "cons": [],',
      '  "risks": [],',
      '  "estimatedComplexity": "medium",',
      '  "demoTrapResistanceScore": 0,',
      '  "productCompletenessScore": 0,',
      '  "modules": [],',
      '  "evidenceRefs": [],',
      '  "confidence": 0,',
      '  "tradeoffSummary": "...",',
      '  "missingEvidenceImpact": "...",',
      '  "conditionsToPreferThisRoute": [],',
      '  "conditionsToRejectThisRoute": []',
      "}",
    ].join("\n"),
  ].join("\n"),
  buildUserPrompt(input: unknown) {
    return jsonInput({
      task: "Generate multiple technical/product strategy routes. Each route must be concrete to the goal and include evidence refs, risks, tradeoffs, and conditions to prefer or reject it. Keep output compact.",
      input,
    });
  },
  outputSchemaName: "strategy-candidates",
  outputSchemaDescription: "Array of strategy candidates with id, title, thesis, targetFit, architectureShape, productCoverage, risks, estimatedComplexity, evidenceRefs, confidence, tradeoffSummary, and missingEvidenceImpact.",
  expectedShape: {
    type: "array" as const,
    minItems: 4,
    itemRequired: ["id", "title", "thesis", "targetFit", "architectureShape", "productCoverage", "securityAndAbuseResistance", "operationalModel", "pros", "cons", "risks", "estimatedComplexity", "demoTrapResistanceScore", "evidenceRefs", "confidence", "tradeoffSummary", "missingEvidenceImpact"],
    itemArrays: [
      { path: "architectureShape", minItems: 1 },
      { path: "productCoverage", minItems: 1 },
      { path: "securityAndAbuseResistance", minItems: 1 },
      { path: "operationalModel", minItems: 1 },
      { path: "pros" },
      { path: "cons" },
      { path: "risks", minItems: 1 },
      { path: "evidenceRefs", minItems: 1 },
      { path: "modules" },
      { path: "conditionsToPreferThisRoute" },
      { path: "conditionsToRejectThisRoute" },
    ],
  },
  examples: [],
  badOutputExamples: commonBadOutputExamples,
  qualityChecklist: [
    ...commonQualityChecklist,
    "mustNotContain:final report",
    "mustNotContain:full architecture document",
  ],
  temperature: 0.25,
  maxRetries: 2,
};