import { commonBadOutputExamples, commonQualityChecklist, jsonInput, thinkingSystemPrompt } from "./common.js";

export const technicalProductizationPlannerPrompt = {
  agentName: "TechnicalProductizationPlanner",
  systemPrompt: [
    thinkingSystemPrompt,
    "You create a technical route productization plan, not implementation code.",
    "Return only one root JSON object with technicalRoutePlan, productizationForecast, problemResolutionPlan, and technicalRouteScorecard.",
    "Use only the compressed input. Do not ask for repository files and do not invent online evidence.",
    "Do not merely repeat RouteDeepDive. Convert route risks into data models, state machines, conflict checks, approval workflows, audit trails, integration boundaries, operations, tests, and migration questions.",
    "For medical intern rotation management, explicitly cover 轮转计划, 科室容量, 带教分配, 请假调岗, 出科考核, 考勤记录, 审批流, 审计日志, 院内身份/人事/考勤/通知集成边界.",
    "If selectedRouteSummary.canProceedToCoding is false, scorecard codingReadiness must be blocked or conditional, never approved.",
  ].join("\n"),
  buildUserPrompt(input: unknown) {
    return jsonInput({
      task: "Generate technical productization artifacts from compressed deliberation input. Keep unresolved blockers visible. Do not hand off to coding unless the input already permits it.",
      input,
    });
  },
  outputSchemaName: "technical-productization-planner-result",
  outputSchemaDescription: "Object with technicalRoutePlan, productizationForecast, problemResolutionPlan, and technicalRouteScorecard.",
  expectedShape: {
    type: "object" as const,
    required: ["technicalRoutePlan", "productizationForecast", "problemResolutionPlan", "technicalRouteScorecard"],
    arrays: [
      {
        path: "technicalRoutePlan.routes",
        minItems: 1,
        itemRequired: [
          "strategyId",
          "routeTitle",
          "recommendedArchitecture",
          "backendModules",
          "frontendBoundaries",
          "databaseModel",
          "stateMachines",
          "permissionModel",
          "conflictDetectionModel",
          "approvalWorkflowModel",
          "auditLogModel",
          "importExportModel",
          "integrationAdapters",
          "deploymentTopology",
          "observabilityPlan",
          "backupAndRecoveryPlan",
          "testingPlan",
          "migrationPlan",
          "codingReadiness",
          "unresolvedTechnicalQuestions",
        ],
      },
      {
        path: "productizationForecast.items",
        minItems: 1,
        itemRequired: [
          "id",
          "scenario",
          "whyLikely",
          "affectedModules",
          "severity",
          "earlyWarningSignal",
          "designCountermeasure",
          "testCaseNeeded",
          "operationalPlaybookNeeded",
        ],
      },
      {
        path: "problemResolutionPlan.problems",
        minItems: 1,
        itemRequired: [
          "problem",
          "rootCause",
          "recommendedSolution",
          "dataModelChange",
          "workflowChange",
          "permissionChange",
          "auditRequirement",
          "validationRule",
          "testCases",
          "operationalFallback",
          "residualRisk",
          "blocksCodingUntilResolved",
        ],
      },
      {
        path: "technicalRouteScorecard.routeScores",
        minItems: 1,
        itemRequired: [
          "strategyId",
          "routeTitle",
          "architectureMaturity",
          "domainModelCompleteness",
          "workflowRobustness",
          "permissionSafety",
          "auditability",
          "integrationReadiness",
          "productizationRisk",
          "testingFeasibility",
          "operationalMaintainability",
          "codingReadiness",
          "finalRecommendation",
        ],
      },
    ],
  },
  examples: [],
  badOutputExamples: commonBadOutputExamples,
  qualityChecklist: [
    ...commonQualityChecklist,
    "mustNotContain:单页 demo",
    "mustNotContain:HTML localStorage",
  ],
  temperature: 0.2,
  maxRetries: 2,
};